// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: project/investor.proto

package project

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Investor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Money    uint64 `protobuf:"varint,2,opt,name=money,proto3" json:"money,omitempty"`
	FullName string `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	UserId   uint32 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *Investor) Reset() {
	*x = Investor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_project_investor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Investor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Investor) ProtoMessage() {}

func (x *Investor) ProtoReflect() protoreflect.Message {
	mi := &file_project_investor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Investor.ProtoReflect.Descriptor instead.
func (*Investor) Descriptor() ([]byte, []int) {
	return file_project_investor_proto_rawDescGZIP(), []int{0}
}

func (x *Investor) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Investor) GetMoney() uint64 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *Investor) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Investor) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddInvestorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Investor *Investor `protobuf:"bytes,1,opt,name=investor,proto3" json:"investor,omitempty"`
}

func (x *AddInvestorRequest) Reset() {
	*x = AddInvestorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_project_investor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddInvestorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInvestorRequest) ProtoMessage() {}

func (x *AddInvestorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_investor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInvestorRequest.ProtoReflect.Descriptor instead.
func (*AddInvestorRequest) Descriptor() ([]byte, []int) {
	return file_project_investor_proto_rawDescGZIP(), []int{1}
}

func (x *AddInvestorRequest) GetInvestor() *Investor {
	if x != nil {
		return x.Investor
	}
	return nil
}

type RemoveInvestorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InvestorId uint32 `protobuf:"varint,1,opt,name=investor_id,json=investorId,proto3" json:"investor_id,omitempty"`
}

func (x *RemoveInvestorRequest) Reset() {
	*x = RemoveInvestorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_project_investor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveInvestorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveInvestorRequest) ProtoMessage() {}

func (x *RemoveInvestorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_investor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveInvestorRequest.ProtoReflect.Descriptor instead.
func (*RemoveInvestorRequest) Descriptor() ([]byte, []int) {
	return file_project_investor_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveInvestorRequest) GetInvestorId() uint32 {
	if x != nil {
		return x.InvestorId
	}
	return 0
}

type MoneyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InvestorId uint32 `protobuf:"varint,1,opt,name=investor_id,json=investorId,proto3" json:"investor_id,omitempty"`
	Money      uint32 `protobuf:"varint,2,opt,name=money,proto3" json:"money,omitempty"`
}

func (x *MoneyRequest) Reset() {
	*x = MoneyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_project_investor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoneyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoneyRequest) ProtoMessage() {}

func (x *MoneyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_investor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoneyRequest.ProtoReflect.Descriptor instead.
func (*MoneyRequest) Descriptor() ([]byte, []int) {
	return file_project_investor_proto_rawDescGZIP(), []int{3}
}

func (x *MoneyRequest) GetInvestorId() uint32 {
	if x != nil {
		return x.InvestorId
	}
	return 0
}

func (x *MoneyRequest) GetMoney() uint32 {
	if x != nil {
		return x.Money
	}
	return 0
}

type InvestProjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InvestorId uint32 `protobuf:"varint,1,opt,name=investor_id,json=investorId,proto3" json:"investor_id,omitempty"`
	Money      uint32 `protobuf:"varint,2,opt,name=money,proto3" json:"money,omitempty"`
	ProjectId  uint32 `protobuf:"varint,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
}

func (x *InvestProjectRequest) Reset() {
	*x = InvestProjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_project_investor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvestProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvestProjectRequest) ProtoMessage() {}

func (x *InvestProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_investor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvestProjectRequest.ProtoReflect.Descriptor instead.
func (*InvestProjectRequest) Descriptor() ([]byte, []int) {
	return file_project_investor_proto_rawDescGZIP(), []int{4}
}

func (x *InvestProjectRequest) GetInvestorId() uint32 {
	if x != nil {
		return x.InvestorId
	}
	return 0
}

func (x *InvestProjectRequest) GetMoney() uint32 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *InvestProjectRequest) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type InvestorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *InvestorResponse) Reset() {
	*x = InvestorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_project_investor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvestorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvestorResponse) ProtoMessage() {}

func (x *InvestorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_investor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvestorResponse.ProtoReflect.Descriptor instead.
func (*InvestorResponse) Descriptor() ([]byte, []int) {
	return file_project_investor_proto_rawDescGZIP(), []int{5}
}

func (x *InvestorResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *InvestorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_project_investor_proto protoreflect.FileDescriptor

var file_project_investor_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x73, 0x74,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x22, 0x66, 0x0a, 0x08, 0x49, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6d, 0x6f,
	0x6e, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x43, 0x0a, 0x12, 0x41, 0x64, 0x64,
	0x49, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2d, 0x0a, 0x08, 0x69, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x49, 0x6e, 0x76, 0x65,
	0x73, 0x74, 0x6f, 0x72, 0x52, 0x08, 0x69, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x22, 0x38,
	0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x76, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x69, 0x6e,
	0x76, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x0c, 0x4d, 0x6f, 0x6e, 0x65,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x76, 0x65,
	0x73, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x69,
	0x6e, 0x76, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x22,
	0x6c, 0x0a, 0x14, 0x49, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x76, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x69, 0x6e,
	0x76, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x22, 0x40, 0x0a,
	0x10, 0x49, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42,
	0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_project_investor_proto_rawDescOnce sync.Once
	file_project_investor_proto_rawDescData = file_project_investor_proto_rawDesc
)

func file_project_investor_proto_rawDescGZIP() []byte {
	file_project_investor_proto_rawDescOnce.Do(func() {
		file_project_investor_proto_rawDescData = protoimpl.X.CompressGZIP(file_project_investor_proto_rawDescData)
	})
	return file_project_investor_proto_rawDescData
}

var file_project_investor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_project_investor_proto_goTypes = []interface{}{
	(*Investor)(nil),              // 0: project.Investor
	(*AddInvestorRequest)(nil),    // 1: project.AddInvestorRequest
	(*RemoveInvestorRequest)(nil), // 2: project.RemoveInvestorRequest
	(*MoneyRequest)(nil),          // 3: project.MoneyRequest
	(*InvestProjectRequest)(nil),  // 4: project.InvestProjectRequest
	(*InvestorResponse)(nil),      // 5: project.InvestorResponse
}
var file_project_investor_proto_depIdxs = []int32{
	0, // 0: project.AddInvestorRequest.investor:type_name -> project.Investor
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_project_investor_proto_init() }
func file_project_investor_proto_init() {
	if File_project_investor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_project_investor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Investor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_project_investor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddInvestorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_project_investor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveInvestorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_project_investor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoneyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_project_investor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvestProjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_project_investor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvestorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_project_investor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_project_investor_proto_goTypes,
		DependencyIndexes: file_project_investor_proto_depIdxs,
		MessageInfos:      file_project_investor_proto_msgTypes,
	}.Build()
	File_project_investor_proto = out.File
	file_project_investor_proto_rawDesc = nil
	file_project_investor_proto_goTypes = nil
	file_project_investor_proto_depIdxs = nil
}
