// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: project/roadmap.proto

package project

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoadMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Dates       *Date  `protobuf:"bytes,2,opt,name=dates,proto3" json:"dates,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Job         string `protobuf:"bytes,5,opt,name=job,proto3" json:"job,omitempty"`
	Target      string `protobuf:"bytes,6,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *RoadMap) Reset() {
	*x = RoadMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_project_roadmap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoadMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoadMap) ProtoMessage() {}

func (x *RoadMap) ProtoReflect() protoreflect.Message {
	mi := &file_project_roadmap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoadMap.ProtoReflect.Descriptor instead.
func (*RoadMap) Descriptor() ([]byte, []int) {
	return file_project_roadmap_proto_rawDescGZIP(), []int{0}
}

func (x *RoadMap) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoadMap) GetDates() *Date {
	if x != nil {
		return x.Dates
	}
	return nil
}

func (x *RoadMap) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoadMap) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoadMap) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *RoadMap) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type CreateRoadmapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roadmap   *RoadMap `protobuf:"bytes,1,opt,name=roadmap,proto3" json:"roadmap,omitempty"`
	ProjectId uint32   `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
}

func (x *CreateRoadmapRequest) Reset() {
	*x = CreateRoadmapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_project_roadmap_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoadmapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoadmapRequest) ProtoMessage() {}

func (x *CreateRoadmapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_roadmap_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoadmapRequest.ProtoReflect.Descriptor instead.
func (*CreateRoadmapRequest) Descriptor() ([]byte, []int) {
	return file_project_roadmap_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoadmapRequest) GetRoadmap() *RoadMap {
	if x != nil {
		return x.Roadmap
	}
	return nil
}

func (x *CreateRoadmapRequest) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type RoadmapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *RoadmapResponse) Reset() {
	*x = RoadmapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_project_roadmap_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoadmapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoadmapResponse) ProtoMessage() {}

func (x *RoadmapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_roadmap_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoadmapResponse.ProtoReflect.Descriptor instead.
func (*RoadmapResponse) Descriptor() ([]byte, []int) {
	return file_project_roadmap_proto_rawDescGZIP(), []int{2}
}

func (x *RoadmapResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RoadmapResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteRoadmapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoadmapId uint32 `protobuf:"varint,1,opt,name=roadmap_id,json=roadmapId,proto3" json:"roadmap_id,omitempty"`
	ProjectId uint32 `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
}

func (x *DeleteRoadmapRequest) Reset() {
	*x = DeleteRoadmapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_project_roadmap_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRoadmapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoadmapRequest) ProtoMessage() {}

func (x *DeleteRoadmapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_roadmap_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoadmapRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoadmapRequest) Descriptor() ([]byte, []int) {
	return file_project_roadmap_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRoadmapRequest) GetRoadmapId() uint32 {
	if x != nil {
		return x.RoadmapId
	}
	return 0
}

func (x *DeleteRoadmapRequest) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

var File_project_roadmap_proto protoreflect.FileDescriptor

var file_project_roadmap_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x1a, 0x12, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9e, 0x01, 0x0a, 0x07, 0x52, 0x6f, 0x61, 0x64, 0x4d, 0x61, 0x70,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x23, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x52, 0x05,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6a,
	0x6f, 0x62, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6a, 0x6f, 0x62, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x61, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a,
	0x07, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x52, 0x6f, 0x61, 0x64, 0x4d, 0x61, 0x70,
	0x52, 0x07, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x22, 0x3f, 0x0a, 0x0f, 0x52, 0x6f, 0x61, 0x64,
	0x6d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x54, 0x0a, 0x14, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x6f, 0x61, 0x64, 0x6d, 0x61, 0x70, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x42,
	0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_project_roadmap_proto_rawDescOnce sync.Once
	file_project_roadmap_proto_rawDescData = file_project_roadmap_proto_rawDesc
)

func file_project_roadmap_proto_rawDescGZIP() []byte {
	file_project_roadmap_proto_rawDescOnce.Do(func() {
		file_project_roadmap_proto_rawDescData = protoimpl.X.CompressGZIP(file_project_roadmap_proto_rawDescData)
	})
	return file_project_roadmap_proto_rawDescData
}

var file_project_roadmap_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_project_roadmap_proto_goTypes = []interface{}{
	(*RoadMap)(nil),              // 0: project.RoadMap
	(*CreateRoadmapRequest)(nil), // 1: project.CreateRoadmapRequest
	(*RoadmapResponse)(nil),      // 2: project.RoadmapResponse
	(*DeleteRoadmapRequest)(nil), // 3: project.DeleteRoadmapRequest
	(*Date)(nil),                 // 4: project.Date
}
var file_project_roadmap_proto_depIdxs = []int32{
	4, // 0: project.RoadMap.dates:type_name -> project.Date
	0, // 1: project.CreateRoadmapRequest.roadmap:type_name -> project.RoadMap
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_project_roadmap_proto_init() }
func file_project_roadmap_proto_init() {
	if File_project_roadmap_proto != nil {
		return
	}
	file_project_date_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_project_roadmap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoadMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_project_roadmap_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoadmapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_project_roadmap_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoadmapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_project_roadmap_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRoadmapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_project_roadmap_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_project_roadmap_proto_goTypes,
		DependencyIndexes: file_project_roadmap_proto_depIdxs,
		MessageInfos:      file_project_roadmap_proto_msgTypes,
	}.Build()
	File_project_roadmap_proto = out.File
	file_project_roadmap_proto_rawDesc = nil
	file_project_roadmap_proto_goTypes = nil
	file_project_roadmap_proto_depIdxs = nil
}
