server:
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    source: "host=localhost user=postgres password=1234 dbname=postgres port=5432 sslmode=disable TimeZone=Asia/Seoul"
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
